### PR TITLE
Some refactoring

### PR DESCRIPTION
**Pull request by corny**
- use bytes.Buffer instead of strings.Join
- use Atoi instead of ParseUint
- use strconv.FormatBool instead of if/else

### CODE REVIEW

**Comment by markuslindenberg** [comment]
Hi Julian,

wow thanks. Looking good so far, I'll merge as soon as I have time to take a deeper look and test.

**Comment by corny** [comment]
Merge?  :bowtie:

**Comment by corny** [comment]
ping

**Comment by corny** [comment]
@markuslindenberg Ping

**Comment by denzs** [comment]
Thanks a lot for this nice contribution! :+1:

**Comment by corny** [comment]
Thanks for merging!

**Comment by denzs** [comment]
btw... feel free to open another PR to add yourself to the AUTHORS file :+1:

**Pull request merged**
